const redirect = require('metalsmith-redirect');

module.exports = function () {
  return redirect({
    '/feed': '/posts.xml',
    '/posts': '/all-posts',
    '/old-posts': '/all-posts',

    // renamed posts
    '/posts/a-history-of-coding-and-computers': '/posts/my-history-of-coding-and-computers',
    '/posts/configure-apache-for-multiple-wordpress-sites': '/posts/configuring-apache-and-fcgi-for-multiple-wordpress-sites',
    '/posts/drupals-on-hold': '/posts/drupal-s-on-hold',
    '/posts/evernotes-clearly': '/posts/evernote-s-clearly',
    '/posts/grunt-painless-build-process': '/posts/grunt-for-a-painless-build-process',
    '/posts/how-i-use-backbone-router': '/posts/how-i-use-backbone-s-router',
    '/posts/ill-have-one-of-your-finest-arduinos-please': '/posts/i-ll-have-one-of-your-finest-arduinos-please',
    '/posts/inaugural-openhack-postmortem': '/posts/inaugural-openhackphx-a-postmortem',
    '/posts/openhack-002-portmortem': '/posts/openhackphx-002-a-postmortem',
    '/posts/remote-backups-with-amazons-s3': '/posts/remote-backups-with-amazon-s-s3',
    '/posts/skirting-isp-torrent-fitlering': '/posts/skirting-isp-torrent-filtering-reset-requests',
    '/posts/slim-jade': '/posts/slim-jade-a-lightweight-php-framework-using-jade-templates',
    '/posts/slim-jade-a-light-weight-php-framework-using-jade-templates': '/posts/slim-jade-a-lightweight-php-framework-using-jade-templates',
    '/posts/static-sites-rock': '/posts/static-websites-rock',
    '/posts/wordpress-out-docpad-in': '/posts/wordpress-is-out-docpad-is-in',
    '/posts/asynchronous-php': '/posts/asynchronous-file-downloads-in-php',

    // old wordpress permalinks
    '/2007/04/09/why-must-computer-oems-suck': '/posts/why-must-computer-oems-suck',
    '/2007/04/12/configuring-access-in-mediawiki': '/posts/configuring-access-in-mediawiki',
    '/2007/04/25/touchpad-speed-in-linux': '/posts/touchpad-speed-in-linux',
    '/2007/09/06/usb-devices-in-virtualbox': '/posts/usb-devices-in-virtualbox',
    '/2007/12/02/python-pylons-and-fastcgi-on-dreamhost': '/posts/python-pylons-and-fastcgi-on-dreamhost',
    '/2007/12/04/ubuntu-firefox-flash-and-sound': '/posts/ubuntu-firefox-flash-and-sound',
    '/2007/12/16/valid-xhtml-and-opening-links-in-new-windows': '/posts/valid-xhtml-and-opening-links-in-new-windows',
    '/2008/01/13/choosing-default-sound-card-in-ubuntu': '/posts/choosing-default-sound-card-in-ubuntu',
    '/2008/02/08/rolling-your-own-deb-package-getting-secure-vpn-tunneling-on-ubuntu': '/posts/rolling-your-own-deb-package-getting-secure-vpn-tunneling-on-ubuntu',
    '/2008/03/23/wordpress-users-check-your-registered-user-list': '/posts/wordpress-users-check-your-registered-user-list',
    '/2008/03/23/my-foray-into-data-recovery': '/posts/my-foray-into-data-recovery',
    '/2008/06/07/skirting-isp-torrent-fitlering': '/posts/skirting-isp-torrent-filtering-reset-requests',
    '/2008/07/04/mootools-i-choose-you': '/posts/mootools-i-choose-you',
    '/2008/08/02/a-history-of-coding-and-computers': '/posts/my-history-of-coding-and-computers',
    '/2008/11/17/drupals-on-hold': '/posts/drupal-s-on-hold',
    '/2009/01/03/building-a-better-captcha': '/posts/building-a-better-captcha',
    '/2008/08/18/farewell-wordpress': '/posts/farewell-wordpress',
    '/2009/01/29/multiple-drive-failures-in-raid-5': '/posts/multiple-drive-failures-in-raid-5',
    '/2009/01/30/fallout-3-terminal-hacker': '/posts/fallout-3-terminal-hacker',
    '/2008/08/23/media-playback-in-ubuntu': '/posts/media-playback-in-ubuntu',
    '/2008/05/27/ill-have-one-of-your-finest-arduinos-please': '/posts/i-ll-have-one-of-your-finest-arduinos-please',
    '/2009/03/11/my-sweet-new-laptop': '/posts/my-sweet-new-laptop',
    '/2009/03/16/how-not-to-sell-mp3s': '/posts/how-not-to-sell-mp3s',
    '/2009/06/14/ubuntu-64-bit-and-adobe-air': '/posts/ubuntu-64-bit-and-adobe-air',
    '/2009/10/01/pptp-vpn-routing-in-ubuntu-using-network-manager': '/posts/pptp-vpn-routing-in-ubuntu-using-network-manager',
    '/2009/10/16/asynchronous-php': '/posts/asynchronous-file-downloads-in-php',
    '/2010/01/06/living-with-pulseaudio-via-pulseaudio-device-chooser': '/posts/living-with-pulseaudio-via-pulseaudio-device-chooser',
    '/2010/03/30/samsung-x360-backlight-control-with-ubuntu': '/posts/samsung-x360-backlight-control-with-ubuntu',
    '/2010/05/11/serving-files-in-internet-explorer-over-https': '/posts/serving-files-in-internet-explorer-over-https',
    '/2009/04/23/ubuntu-64-bit-firefox-and-flash': '/posts/ubuntu-64-bit-firefox-and-flash',
    '/2009/02/09/remote-backups-with-amazons-s3': '/posts/remote-backups-with-amazon-s-s3',
    '/2011/11/03/ubuntu-node-and-heroku': '/posts/ubuntu-node-and-heroku',
    '/2010/05/13/tweaking-gnome-for-low-resolution-displays': '/posts/tweaking-gnome-for-low-resolution-displays',
    '/2012/01/14/trello-is-awesome': '/posts/trello-is-awesome',
    '/2012/03/29/slim-jade': '/posts/slim-jade-a-lightweight-php-framework-using-jade-templates',
    '/2012/05/14/my-move-to-mac': '/posts/my-move-to-mac',
    '/2012/02/10/evernotes-clearly': '/posts/evernote-s-clearly',
    '/2010/05/26/atheros-ar8131-and-linux': '/posts/atheros-ar8131-and-linux',
    '/2012/01/06/validating-startup-ideas': '/posts/validating-startup-ideas',
    '/2012/06/14/why-i-use-sublime-text': '/posts/why-i-use-sublime-text',
    '/2012/05/28/easy-screenshot-sharing-in-osx': '/posts/easy-screenshot-sharing-in-osx',
    '/2012/06/07/git-flow': '/posts/git-flow',
    '/2012/06/03/more-git-magic': '/posts/more-git-magic',
    '/2012/06/10/hello-there-windows-phone': '/posts/hello-there-windows-phone',
    '/2012/11/16/going-back-to-neutral': '/posts/going-back-to-neutral',
    '/2013/01/05/stripe': '/',
    '/2013/02/14/responsive-layouts-with-stylus': '/posts/responsive-layouts-with-stylus',
    '/2012/05/24/git-info-in-your-bash-prompt': '/posts/git-info-in-your-bash-prompt',
    '/2012/12/02/hacking-recaptcha': '/posts/cheating-recaptcha',
  });
};